### ISSUE TITLE
如何获取自身的Node

### ISSUE THREAD

**Issue by vinci2015** [ticwear/sdk#14]
我需要记录手表自身的一些信息

**Comment by Tinker-S** [comment]
private Collection<String> getNodes() {
        HashSet<String> results = new HashSet<String>();
        NodeApi.GetConnectedNodesResult nodes =
                Wearable.NodeApi.getConnectedNodes(mMobvoiApiClient).await();

        for (Node node : nodes.getNodes()) {
            results.add(node.getId());
        }

        return results;
    }

**Comment by bitristan** [comment]
使用 Wearable.NodeApi.getLocalNode()方法就可以获取自身的Node
