### ISSUE TITLE
Ticwatch2独立手表应用支持Wifi传输数据吗

### ISSUE THREAD

**Issue by outlier888** [ticwear/sdk#21]
我们要开发一个行业应用，需要把手表上的传感器数据通过Wifi传输到服务器上，API能支持吗？

**Comment by auxor** [comment]
可以使用wifi上传，直接发起网络请求就可以；如果连接了蓝牙，也可以直接发起网络请求，只是比较慢；如果是连接的3G，那么需要请求权限，http://developer.chumenwenwen.com/doc/ticwear.html#doc/2/31
