### ISSUE TITLE
JCenter 停止服务啦 求SDK

### ISSUE THREAD

**Issue by ichenhe** [ticwear/sdk#26]
虽然官方承诺永久保留现有的内容供下载，**但是你们的SDK没有提及到JCenter啊，在自己的账户下，所以被删掉了。**

我知道 Ticwear 不维护了，但是还有存量用户需要作兼容，麻烦传一个 `mobvoi-api-1.1.1` AAR 文件吧 😭

**Comment by bitristan** [comment]
[mobvoi_api_1.1.1.aar](https://github.com/ticwear/sdk/blob/master/dist/mobvoi-api-1.1.1.aar)

抱歉，先用着这个试试

**Comment by ichenhe** [comment]
OK 啦 感谢
